meta_product_name: "Hello World"
meta_title: "Hello World - A platform that brings coders to one place"
meta_description: "A platform that brings coders to one place"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
